CREATE TABLE AGENDA
(
	CODIGO INT auto_increment PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE CHAR(11) NOT NULL,
    LINKEDIN VARCHAR(100),
    ENDERECO VARCHAR(50),
    DATA_NASC DATE
);

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password;
